### PR TITLE
Set User Button GPIO to ACTIVE_HIGH in gpio_keys config

### PR DESCRIPTION
**Pull request by andiaye33**

### CODE REVIEW

**Comment by clementlgl** [comment]
@andiaye33 Can you rebase the branch? Thank you

**Comment by bperraudin** [comment]
@andiaye33 Please resolve conflicts.

**Review by bperraudin — CHANGES_REQUESTED** [review]
The rebase has once again not been done correctly: you merged main into this branch.

You should **NEVER** merge anything into a PR branch, you must **REBASE**.

**Comment by clementlgl** [comment]
@andiaye33 Please test before push? An error has occurred during CI...
https://github.com/catie-aq/zephyr_zest-core-fmlr-72/actions/runs/11969615742/job/33372101914?pr=20

**Comment by andiaye33** [comment]
OK

**Comment by clementlgl** [comment]
@andiaye33 Can you squash the commits?

**Review by clementlgl — APPROVED** [review]

**Comment by andiaye33** [comment]
@clementlgl : everithing is ok now

https://github.com/catie-aq/zephyr_zest-core-fmlr-72/actions/runs/11969615742?pr=20

**Review by clementlgl — APPROVED** [review]

**Review by bperraudin — APPROVED** [review]

**Pull request merged**
